@startuml

class AAUOC{
newLocation(I: Location) : void
newEvent (e : Event) : void
newPerson (p : Person): void
informEvent(e : Event) : void
register(m : Member,e : Event) : void
}

class Location{
description: String
address: String
}
AAUOC o-- "0..*" Location

class Event{
date : Date
description : String

}
Location "1" -- "0..*" Event : isLocatedIn
AAUOC o-- "0..*" Event

class Person{
name : String
}
AAUOC o-- "0..*" Person

class Member{
e-mail : String
}
Person <|-- Member
Event "0..*" -- "0..*" Member : attendsTo

class Conference{
max_attendees : Integer
}
Event <|-- Conference
Person "0..*" -- "0..*" Conference : attendsTo

class BoardMeeting
Event <|-- BoardMeeting

class BoardMember
BoardMember "0..*" -- "0..*" BoardMeeting : attendsTo
Member <|-- BoardMember

@enduml