@startuml

class AAUOC{
newLocation(I: Location) : void
newEvent (e : Event) : void
newPerson (p : Person): void
informEvent(e : Event) : void
register(m : Member,e : Event) : void
}

class Location{
description: String
address: String
}
AAUOC o-- Location



class Event{
date : Date
description : String

assign(I: Location) : void
}
Location -- Event
AAUOC o-- Event

class Person{
name : String
}
AAUOC o-- Person

class Member{
e-mail : String
}
Person <|-- Member
Event -- Member

class Conference{
max_attendees : Integer
}
Event <|-- Conference
Person -- Conference

class BoardMeeting
Event <|-- BoardMeeting

class BoardMember
BoardMember -- BoardMeeting
Member <|-- BoardMember

@enduml